humanrate/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'talks#index'
  resources :talks, only: [:index, :show] do
    resources :votes, only: [:create]
  end
end

humanrate/app/models/talk.rb
class Talk < ActiveRecord::Base
  validates :name, presence: true
  has_many :votes
end

humanrate/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

humanrate/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :talk
end

humanrate/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

humanrate/app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @talks = Talk.all
  end

  def show
    @talk = Talk.find(params[:id])
  end
end

humanrate/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    vote = Vote.create(vote_params)
    redirect_to vote.talk
  end

  private

  def vote_params
    params.permit(:note, :talk_id)
  end
end

humanrate/app/helpers/application_helper.rb
module ApplicationHelper
end

humanrate/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Humanrate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

humanrate/app/views/talks/_talk.erb
<h2><%= link_to talk.name, talk %></h2>
<p><%= talk.description %></p>
<p>Votes : <strong><%= talk.votes.size %></strong></p>

humanrate/app/views/talks/index.erb
<h1>Liste des talks</h1>
<%= render @talks %>

humanrate/app/views/talks/show.erb
<h1>Détail d'un talk</h1>
<%= link_to 'Retour à la liste', root_path %>
<%= render @talk %>

<h3>Voter pour ce talk :</h3>
<%= form_for @talk.votes.build, url: talk_votes_path(@talk) do |f| %>
  <%= select_tag(:note, options_for_select([1,2,3])) %>
  <%= f.submit 'Voter pour ce talk' %>
<% end %>